server:
  port: 9200

spring:
  application:
    name: lgmall-gateway

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.10:8848

    sentinel:
      transport:
        #配置sentinel dashboard地址
        dashboard: 192.168.56.10:8858

    gateway:
      routes:
        - id: product_route
          uri: lb://lgmall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        - id: cart_route
          uri: lb://lgmall-cart
          predicates:
            - Path=/api/cart/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        - id: admin_route
          uri: lb://lgmall-admin
          predicates:
            - Path=/api/admin/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        - id: order_route
          uri: lb://lgmall-order
          predicates:
            - Path=/api/order/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

          #所以访问 lgmall.com的时候，就会路由到登录服务去
        - id: lgmall_host_route
          uri: lb://lgmall-product
          predicates:
            - Host=lgmall.com

        - id: lgmall_product_route
          uri: lb://lgmall-product
          predicates:
            - Host=product.lgmall.com

        - id: lgmall_admin_route
          uri: lb://lgmall-admin
          predicates:
            - Host=admin.lgmall.com

        - id: lgmall_cart_route
          uri: lb://lgmall-cart
          predicates:
            - Host=cart.lgmall.com

        - id: lgmall_order_route
          uri: lb://lgmall-order
          predicates:
            - Host=order.lgmall.com





#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'