server:
  port: 9400

spring:
  application:
    name: lgmall-product

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.100:8848

    sentinel:
      transport:
        #配置sentinel dashboard地址
        dashboard: 192.168.56.100:8858

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.56.10:3306/lgmall_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

  rabbitmq:
    publisher-confirm-type: correlated #生产者消息确认类型，会调用confirm方法
    publisher-returns: true  #消息被路由到队列失败则会返回调用方法
    host: 192.168.56.100
    port: 5672
    username: guest
    password: guest
    listener:
      type: simple
      simple:
        acknowledge-mode: manual #消费者手动ack确认
        prefetch: 1 #限制每次发送一条数据。
        concurrency: 1 #同一个队列启动几个消费者,最少消费者数量
        max-concurrency: 3 #启动消费者最大数量
        #重试策略相关配置
        retry:
          enabled: true #是否支持重试
          max-attempts: 5 #最大重试次数
          stateless: false

#开启feign对sentinel的支持
feign:
  sentinel:
    enabled: true
