server:
  port: 9000

spring:
  application:
    name: lgmall-admin

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.100:8848

    sentinel:
      transport:
        #配置sentinel dashboard地址
        dashboard: 192.168.56.100:8858
  #数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.56.100:3306/lgmall_ums?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root


#开启feign对sentinel的支持
feign:
  sentinel:
    enabled: true
  thymeleaf:
    cache: false

#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'

